---
title: "House Jobs District"
author: "Sethu Odayappan"
date: "6/12/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages('dplyr')
library(dplyr)
```


```{r}
housejobs = read.csv("housejobsfulldistrict.csv")
reps.info = read.csv("MA 2018 House of Reps. - Sheet3 (2).csv")
data.total = cbind(area, reps.info)

byjob = group_by (housejobs, Job.Category)
occupation <- summarise(byjob, AverageContribution = mean(Amount, na.rm=TRUE), TotalAmount = sum(Amount, na.rm=TRUE))
```
```{r}
valid = housejobs[housejobs$district !="161" & housejobs$district !="162"& housejobs$district !="163", ]
district = valid[valid$In.District == "0",]
table(district$Job.Category)/table(valid$Job.Category)
```

```{r}
bydistrict = group_by (housejobs, Recipient)
area <- summarise(bydistrict, AverageContribution = mean(Amount, na.rm=TRUE), TotalAmount = sum(Amount, na.rm=TRUE), test = sum(In.District, na.rm=TRUE))

reps = table(valid$Recipient)
counttotal = data.frame(reps)

area$totalcount = counttotal$Freq
area$out.of.district = (area$test / area$totalcount)

write.csv(area, file = "housereporder.csv")

anovatest = aov(In.District ~ Job.Category, data = valid)
summary(anovatest)
```

```{r}
replist.data = read.csv("housereporder (2).csv")
valid.replist = replist.data[replist.data$Billspassed != "-1",]
model1 = lm(valid.replist$Billspassed ~ valid.replist$out.of.district)
summary(model1)
```


```{r}
#Data Analysis by Rep

Democrat = data.total[data.total$Party == "Democrat",]
Republican = data.total[data.total$Party == "Republican",]
mean(Democrat$out.of.district)
mean(Republican$out.of.district)

Partisan = data.total[data.total$Party == "Democrat" | data.total$Party == "Republican",]
Comp = data.total[data.total$Competition == "Yes" | data.total$Competition == "No",]

t.test(Partisan$out.of.district ~ Partisan$Party)
t.test(data.total$out.of.district ~ data.total$Sex)
t.test(Comp$out.of.district ~ Comp$Competition)
t.test(data.total$out.of.district ~ data.total$Result)

model1 = lm(data.total$eighty.percentile ~ data.total$out.of.district)
summary(model1)

model2 = lm(data.total$twenty.percentile ~ data.total$out.of.district)
summary(model2)

model3 = lm(data.total$median.income ~ data.total$out.of.district)
summary(model3)

model4 = lm(data.total$AverageContribution ~ data.total$out.of.district)
summary(model4)
```








